version: 2.1
jobs:
  build:
    working_directory: /srv/jekyll
    docker:
      - image: jekyll/builder:4.0
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: |
            apk add --update nodejs npm
            bundle install
      - run: 
          name: Execute Build script
          command: |
            sh build.sh
      - persist_to_workspace:
          root: ./
          paths: _site/*
  publish:
    docker:
      - image: bitnami/git:latest
    steps:
      - attach_workspace:
          at: ./generated
      - run:
          name: Clone old website
          command: |
            git clone $GENERATED_SITE_REPO repo
      - run:
          name: Copy newly generated files
          command: |
            cp -a ./generated/_site/* repo/
      - run:
          name: Change working directory
          command: cd repo
      - run:
          name: Set up personal info
          command: |
            git config user.email $GENERATED_SITE_REPO_EMAIL
            git config user.name $GENERATED_SITE_REPO_OWNER
      - run:
          name: Commit and Push to repository
          command: |
            git add .
            git commit "New changes - Generated at "$(date +%F)
            git push
workflows:
  build_and_publish:
    jobs:
      - build
      - publish:
          requires:
            - build
